# Generated by Django 2.2.13 on 2020-06-17 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_customtext_test1'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='test2',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
